### ISSUE TITLE
Operation ReadMe

### ISSUE THREAD

**Issue by johnisanerd** [DexterInd/GoogleCloudDerby#2]
@ELundby45 , could you add a readme somewhere that goes over how to operate this baby?

**Comment by ELundby45** [comment]
@johnisanerd I can certainly do that. I already have the README here: https://github.com/DexterInd/GoogleCloudDerby/tree/sdcard-setup-script/sdcard_setup

Do you want more information around the individual tasks that get ran?

**Comment by johnisanerd** [comment]
No, I totally missed that.  I guess the installation is really just npm install, right?  That's it?

While I'm thinking of it, can we paste this link everywhere inside here?  https://shop.dexterindustries.com/cloud-derby-robot-kit/
